{{- if .Values.regru.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "webhook.fullname" . }}-credentials
  namespace: {{ .Values.certManagerNamespace }}
  labels:
    {{- include "webhook.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.regru.username | quote }}
  password: {{ .Values.regru.password | quote }}
{{- end }}
